# Generated by Django 5.2.3 on 2025-06-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_telegramuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
